// Plugins
import './plugins/send-message';
import './plugins/configuration-openings';
//import './plugins/configuration-test';

import './plugins/messages-log';
import './plugins/messages';
import './plugins/users';
import './plugins/admins';
import './plugins/users-suspend';
import './plugins/users-data';
import './plugins/chat-demo';
import './plugins/funnel';
import './plugins/simulator';
import './plugins/content';
import './plugins/content-image';
import './plugins/knowledge-base';
import './plugins/carousel';
import './plugins/welcome-message';
import './plugins/surveys';
